/** Rubros base predefinidos por tipo de obra.
 *  Se usan para pre-poblar versiones de presupuesto nuevas
 *  y como contexto enviado a la IA. */
export const OBRA_TYPE_TEMPLATES: Record<string, string[]> = {
  VIVIENDA_UNIFAMILIAR: [
    'Movimiento de tierras y demoliciones',
    'Fundaciones',
    'Estructura de hormigón',
    'Mampostería',
    'Cubiertas e impermeabilizaciones',
    'Revoques y enlucidos',
    'Revestimientos y pisos',
    'Carpintería de madera',
    'Carpintería metálica y herrería',
    'Instalación sanitaria',
    'Instalación eléctrica',
    'Pintura',
  ],
  EDIFICIO_MULTIFAMILIAR: [
    'Movimiento de tierras y excavaciones',
    'Fundaciones y pilotes',
    'Estructura de hormigón armado',
    'Mampostería y tabiquería',
    'Cubiertas e impermeabilizaciones',
    'Revoques y revestimientos',
    'Pisos y contrapisos',
    'Carpintería de madera',
    'Carpintería metálica y herrería',
    'Instalación sanitaria y pluvial',
    'Instalación eléctrica y baja tensión',
    'Ascensor e instalaciones especiales',
    'Pintura y terminaciones',
    'Espacios comunes y exteriores',
  ],
  INDUSTRIAL: [
    'Movimiento de tierras y preparación del terreno',
    'Fundaciones y losas industriales',
    'Estructura metálica principal',
    'Cubierta y cerramiento',
    'Pisos industriales',
    'Instalación eléctrica',
    'Instalación sanitaria y pluvial',
    'Instalaciones especiales',
    'Equipamiento industrial',
    'Accesos y exteriores',
    'Pintura anticorrosiva y terminaciones',
  ],
  COMERCIAL: [
    'Demoliciones y preparación',
    'Fundaciones y estructura',
    'Cerramientos y fachada',
    'Cubiertas',
    'Revestimientos y pisos',
    'Carpintería y vidrios',
    'Instalación eléctrica e iluminación',
    'Instalación sanitaria',
    'Climatización (HVAC)',
    'Señalética y equipamiento',
    'Pintura y terminaciones',
  ],
  EDUCACIONAL: [
    'Movimiento de tierras',
    'Fundaciones',
    'Estructura',
    'Mampostería',
    'Cubiertas',
    'Revoques y revestimientos',
    'Pisos',
    'Carpintería',
    'Instalación sanitaria',
    'Instalación eléctrica',
    'Climatización y ventilación',
    'Mobiliario y equipamiento escolar',
    'Pintura',
    'Espacios exteriores y patio',
  ],
  SALUD: [
    'Demoliciones y acondicionamiento',
    'Fundaciones y estructura',
    'Mampostería y tabiquería especial',
    'Cubiertas e impermeabilizaciones',
    'Revestimientos cerámicos sanitarios',
    'Pisos vinílicos y especiales',
    'Carpintería y puertas corta-fuego',
    'Instalación sanitaria y gases medicinales',
    'Instalación eléctrica y UPS',
    'Climatización y flujos laminares',
    'Equipamiento médico-hospitalario',
    'Pintura epoxi y terminaciones',
  ],
  OFICINAS: [
    'Acondicionamiento y demoliciones',
    'Estructura y refuerzos',
    'Tabiquería seca (drywall)',
    'Cielorrasos',
    'Pisos flotantes y alfombras',
    'Carpintería y vidrios',
    'Instalación eléctrica y telecomunicaciones',
    'Instalación sanitaria',
    'Climatización (VRF/fan coil)',
    'Iluminación LED',
    'Mobiliario y equipamiento',
    'Pintura y terminaciones',
  ],
  OTRO: [
    'Movimiento de tierras',
    'Fundaciones',
    'Estructura',
    'Cerramientos',
    'Cubiertas',
    'Revestimientos y pisos',
    'Carpintería',
    'Instalación sanitaria',
    'Instalación eléctrica',
    'Instalaciones especiales',
    'Pintura y terminaciones',
  ],
}

export const RUBRO_COLORS = [
  '#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6',
  '#06b6d4', '#f97316', '#84cc16', '#ec4899', '#14b8a6',
  '#6366f1', '#d97706', '#dc2626', '#7c3aed', '#0891b2',
]

export function getTemplateForObraType(obraType: string | null | undefined): string[] {
  if (!obraType) return OBRA_TYPE_TEMPLATES.OTRO
  return OBRA_TYPE_TEMPLATES[obraType] ?? OBRA_TYPE_TEMPLATES.OTRO
}
